In [1]:
import pandas as pd
import numpy as np

### Answer 1

In [2]:
def vandermonde(iparray,n,increasing=False):
    if not increasing:
        
        mat = np.array([element**(n-i-1) for element in iparray for i in range(n)]).reshape(iparray.size,n)
        
    elif increasing:
        
        mat = np.array([element**i for element in iparray for i in range(n)]).reshape(iparray.size,n)
        
    return mat

In [3]:
iparray = np.array([1,2,3,4,5])
n = 5

In [4]:
vandermonde(iparray,n,increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [5]:
vandermonde(iparray,n,increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

### Answer 2

In [6]:
def mov_avg(iparray, k) :
    ip_shape = iparray.shape[0]
    
    output = np.zeros(ip_shape - k + 1)
    
    for i in range(k, ip_shape + 1):
        output[i-k] = iparray[i-k:i].mean()
    
    return output   

In [7]:
a = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
win_size = 3
mov_avg(a, win_size)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])